"""add marketplace tables

Revision ID: 3ef7a4fe1172
Revises: 3874b4bfa15f
Create Date: 2026-03-15 22:12:03.945288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '3ef7a4fe1172'
down_revision = '3874b4bfa15f'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())

    if 'marketplace_categories' not in tables:
        op.create_table(
            'marketplace_categories',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('slug', sa.String(length=100), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('icon', sa.String(length=50), nullable=True),
            sa.Column('sort_order', sa.Integer(), nullable=True),
            sa.Column('allowed_types', sa.JSON(), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name'),
            sa.UniqueConstraint('slug')
        )

    if 'marketplace_sellers' not in tables and 'users' in tables:
        op.create_table(
            'marketplace_sellers',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('verification_status', sa.String(length=20), nullable=False),
            sa.Column('reputation_score', sa.Float(), nullable=True),
            sa.Column('delivery_history_count', sa.Integer(), nullable=True),
            sa.Column('dispute_count', sa.Integer(), nullable=True),
            sa.Column('specialization_categories', sa.JSON(), nullable=True),
            sa.Column('bio', sa.Text(), nullable=True),
            sa.Column('total_earned_cents', sa.Integer(), nullable=True),
            sa.Column('pending_payout_cents', sa.Integer(), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id']),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('user_id')
        )

    if 'marketplace_listings' not in tables and 'marketplace_categories' in set(sa.inspect(bind).get_table_names()) and 'marketplace_sellers' in set(sa.inspect(bind).get_table_names()):
        op.create_table(
            'marketplace_listings',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('seller_id', sa.Integer(), nullable=False),
            sa.Column('category_id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(length=255), nullable=False),
            sa.Column('description', sa.Text(), nullable=False),
            sa.Column('item_type', sa.String(length=100), nullable=True),
            sa.Column('price_cents', sa.Integer(), nullable=False),
            sa.Column('currency', sa.String(length=3), nullable=False),
            sa.Column('file_url', sa.Text(), nullable=True),
            sa.Column('file_name', sa.String(length=255), nullable=True),
            sa.Column('file_size_bytes', sa.Integer(), nullable=True),
            sa.Column('file_type', sa.String(length=50), nullable=True),
            sa.Column('preview_images', sa.JSON(), nullable=True),
            sa.Column('tags', sa.JSON(), nullable=True),
            sa.Column('downloads_count', sa.Integer(), nullable=True),
            sa.Column('views_count', sa.Integer(), nullable=True),
            sa.Column('rating', sa.Float(), nullable=True),
            sa.Column('rating_count', sa.Integer(), nullable=True),
            sa.Column('status', sa.String(length=20), nullable=False),
            sa.Column('rejection_reason', sa.Text(), nullable=True),
            sa.Column('is_boosted', sa.Boolean(), nullable=True),
            sa.Column('boost_expires_at', sa.DateTime(), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['category_id'], ['marketplace_categories.id']),
            sa.ForeignKeyConstraint(['seller_id'], ['marketplace_sellers.id']),
            sa.PrimaryKeyConstraint('id')
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milestones_completed', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('tasks_completed', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('tasks_on_time', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('stripe_connect_account_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('collaborations_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('reputation_score', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
        batch_op.add_column(sa.Column('milestones_on_time', sa.INTEGER(), server_default=sa.text('0'), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payout_id', sa.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milestones_completed', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('last_activity_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('milestones_total', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('execution_score', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
        batch_op.add_column(sa.Column('crowdfunding_unlocked', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('activity_score', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
        batch_op.add_column(sa.Column('crowdfunding_unlocked_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('lifecycle_state', sa.VARCHAR(length=50), server_default=sa.text("'active'"), nullable=True))

    with op.batch_alter_table('post_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.BLOB(), nullable=True))
        batch_op.drop_column('media_url')

    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('readiness_breakdown', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('problem_statement', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('required_roles', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('risk_level', sa.VARCHAR(length=20), server_default=sa.text("'medium'"), nullable=True))
        batch_op.add_column(sa.Column('readiness_score', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
        batch_op.add_column(sa.Column('roadmap_items', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('vision_state', sa.VARCHAR(length=50), server_default=sa.text("'public'"), nullable=True))
        batch_op.add_column(sa.Column('outcome_goal', sa.TEXT(), nullable=True))

    with op.batch_alter_table('event_token_balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('event_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('earned_total', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('spent_total', sa.INTEGER(), nullable=True))

    op.create_table('escrow_transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('payer_id', sa.INTEGER(), nullable=False),
    sa.Column('payee_id', sa.INTEGER(), nullable=False),
    sa.Column('payer_balance_id', sa.INTEGER(), nullable=False),
    sa.Column('payee_balance_id', sa.INTEGER(), nullable=True),
    sa.Column('amount_cents', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('reference_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reference_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('funded_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('released_at', sa.DATETIME(), nullable=True),
    sa.Column('disputed_at', sa.DATETIME(), nullable=True),
    sa.Column('cancelled_at', sa.DATETIME(), nullable=True),
    sa.Column('resolution_note', sa.TEXT(), nullable=True),
    sa.Column('resolved_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['payee_balance_id'], ['balances.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payer_balance_id'], ['balances.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visibility_boosts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('crystal_wallet_id', sa.INTEGER(), nullable=False),
    sa.Column('boost_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('crystals_spent', sa.INTEGER(), nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('target_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('duration_hours', sa.INTEGER(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['crystal_wallet_id'], ['crystal_wallets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crystal_wallets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.INTEGER(), nullable=False),
    sa.Column('total_earned', sa.INTEGER(), nullable=False),
    sa.Column('total_spent', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('video_usage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('usage_date', sa.DATE(), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_date', name=op.f('uq_user_video_day'))
    )
    with op.batch_alter_table('video_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_usage_user_id'), ['user_id'], unique=False)

    op.create_table('balance_transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('balance_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tx_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('balance_before', sa.INTEGER(), nullable=False),
    sa.Column('balance_after', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('reference_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reference_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('stripe_payment_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['balance_id'], ['balances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balances',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('available', sa.INTEGER(), nullable=False),
    sa.Column('pending', sa.INTEGER(), nullable=False),
    sa.Column('escrow_locked', sa.INTEGER(), nullable=False),
    sa.Column('total_deposited', sa.INTEGER(), nullable=False),
    sa.Column('total_withdrawn', sa.INTEGER(), nullable=False),
    sa.Column('total_paid_out', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('crystal_transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('crystal_wallet_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('direction', sa.VARCHAR(length=6), nullable=False),
    sa.Column('usage_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('balance_before', sa.INTEGER(), nullable=False),
    sa.Column('balance_after', sa.INTEGER(), nullable=False),
    sa.Column('reference_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['crystal_wallet_id'], ['crystal_wallets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('marketplace_listings')
    op.drop_table('marketplace_sellers')
    op.drop_table('marketplace_categories')
    # ### end Alembic commands ###
