"""add ERP tables

Revision ID: 672e6bf46139
Revises: 45e070148f4f
Create Date: 2026-04-20 15:59:21.973287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672e6bf46139'
down_revision = '45e070148f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('builder_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('sector_interests', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('execution_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.String(length=50), nullable=True))

    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_column('activated_as_startup_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activated_as_startup_id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('builder_profiles', schema=None) as batch_op:
        batch_op.drop_column('availability')
        batch_op.drop_column('execution_score')
        batch_op.drop_column('sector_interests')
        batch_op.drop_column('skill_tags')

    # ### end Alembic commands ###
