"""add storage_used_mb to user

Revision ID: 6b2712972bca
Revises: a07bba3604e0
Create Date: 2026-02-26 14:58:47.405325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2712972bca'
down_revision = 'a07bba3604e0'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    def table_exists(table_name):
        return table_name in inspector.get_table_names()

    def column_exists(table_name, column_name):
        if not table_exists(table_name):
            return False
        return column_name in {column['name'] for column in inspector.get_columns(table_name)}

    # ### commands auto generated by Alembic - please adjust! ###
    if table_exists('_alembic_tmp_conversation_participants'):
        op.drop_table('_alembic_tmp_conversation_participants')

    if table_exists('conversation_participants') and column_exists('conversation_participants', 'is_archived'):
        with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
            batch_op.alter_column('is_archived',
                   existing_type=sa.INTEGER(),
                   type_=sa.Boolean(),
                   existing_nullable=False,
                   existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.alter_column('is_archived',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    op.create_table('_alembic_tmp_conversation_participants',
    sa.Column('conversation_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('joined_at', sa.DATETIME(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_hidden', sa.BOOLEAN(), nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('archived_at', sa.DATETIME(), nullable=True),
    sa.Column('is_pinned', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('pinned_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id')
    )
    # ### end Alembic commands ###
