"""fix missing stripe column

Revision ID: 8792668c20b9
Revises: e9284a7e32aa
Create Date: 2026-03-17 18:01:33.608577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8792668c20b9'
down_revision = 'e9284a7e32aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_transactions_balance_id'))
        batch_op.drop_index(batch_op.f('ix_balance_transactions_user_id'))

    with op.batch_alter_table('balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balances_user_id'))

    with op.batch_alter_table('crystal_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crystal_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_crystal_transactions_wallet_id'))

    with op.batch_alter_table('crystal_wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crystal_wallets_user_id'))

    with op.batch_alter_table('escrow_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escrow_payee_id'))
        batch_op.drop_index(batch_op.f('ix_escrow_payer_id'))
        batch_op.drop_index(batch_op.f('ix_escrow_status'))

    with op.batch_alter_table('event_token_balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('earned_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('spent_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.alter_column('last_activity_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('crowdfunding_unlocked_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payout_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_connect_account_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reputation_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('milestones_completed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('milestones_on_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tasks_completed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tasks_on_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('collaborations_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('visibility_boosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visibility_boosts_expires_at'))
        batch_op.drop_index(batch_op.f('ix_visibility_boosts_is_active'))
        batch_op.drop_index(batch_op.f('ix_visibility_boosts_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visibility_boosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visibility_boosts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visibility_boosts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_visibility_boosts_expires_at'), ['expires_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('collaborations_count')
        batch_op.drop_column('tasks_on_time')
        batch_op.drop_column('tasks_completed')
        batch_op.drop_column('milestones_on_time')
        batch_op.drop_column('milestones_completed')
        batch_op.drop_column('reputation_score')
        batch_op.drop_column('stripe_connect_account_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('stripe_payout_id')

    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.alter_column('crowdfunding_unlocked_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('last_activity_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('event_token_balances', schema=None) as batch_op:
        batch_op.drop_column('expires_at')
        batch_op.drop_column('spent_total')
        batch_op.drop_column('earned_total')
        batch_op.drop_column('event_name')

    with op.batch_alter_table('escrow_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escrow_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_escrow_payer_id'), ['payer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_escrow_payee_id'), ['payee_id'], unique=False)

    with op.batch_alter_table('crystal_wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crystal_wallets_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('crystal_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crystal_transactions_wallet_id'), ['crystal_wallet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crystal_transactions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balances_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('balance_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_transactions_balance_id'), ['balance_id'], unique=False)

    # ### end Alembic commands ###
