"""add SF Meet tables

Revision ID: 8918ffe055eb
Revises: 03f8e9943718
Create Date: 2026-04-27 18:22:17.664375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8918ffe055eb'
down_revision = '03f8e9943718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meet_meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meeting_type', sa.Enum('startup_team', 'vision_review', 'milestone_review', 'mentor_session', 'customer_call', 'investor_call', 'internal_org', 'dispute_review', name='meetingtype'), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'live', 'ended', 'processing', 'indexed', 'archived', 'cancelled', name='meetingstatus'), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('startup_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('vision_id', sa.Integer(), nullable=True),
    sa.Column('linked_milestone_ids', sa.JSON(), nullable=True),
    sa.Column('linked_task_ids', sa.JSON(), nullable=True),
    sa.Column('scheduled_start_at', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end_at', sa.DateTime(), nullable=True),
    sa.Column('actual_start_at', sa.DateTime(), nullable=True),
    sa.Column('actual_end_at', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('visibility_scope', sa.Enum('private', 'invited_only', 'startup_members', 'organization', 'mentor_visible', 'advisor_visible', name='visibilityscope'), nullable=True),
    sa.Column('recording_enabled', sa.Boolean(), nullable=True),
    sa.Column('transcription_enabled', sa.Boolean(), nullable=True),
    sa.Column('live_notes_enabled', sa.Boolean(), nullable=True),
    sa.Column('annotation_enabled', sa.Boolean(), nullable=True),
    sa.Column('agenda_doc_id', sa.String(length=255), nullable=True),
    sa.Column('live_notes_doc_id', sa.String(length=255), nullable=True),
    sa.Column('summary_doc_id', sa.String(length=255), nullable=True),
    sa.Column('transcript_file_id', sa.String(length=255), nullable=True),
    sa.Column('recording_file_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meet_action_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='actionitempriority'), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', 'cancelled', name='actionitemstatus'), nullable=True),
    sa.Column('linked_milestone_id', sa.Integer(), nullable=True),
    sa.Column('linked_task_id', sa.Integer(), nullable=True),
    sa.Column('source_timestamp', sa.Integer(), nullable=True),
    sa.Column('ai_extracted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meet_meeting.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meet_artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.Enum('recording', 'transcript', 'summary', 'notes', 'whiteboard', 'annotation', 'screenshot', name='artifacttype'), nullable=False),
    sa.Column('drive_file_id', sa.String(length=500), nullable=True),
    sa.Column('startup_id', sa.Integer(), nullable=True),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('file_size_mb', sa.Float(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meet_meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meet_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meet_meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meet_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('decision_statement', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('owner_ids_json', sa.JSON(), nullable=True),
    sa.Column('linked_milestone_ids', sa.JSON(), nullable=True),
    sa.Column('linked_doc_ids', sa.JSON(), nullable=True),
    sa.Column('source_timestamp', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'actioned', 'closed', 'reversed', name='decisionstatus'), nullable=True),
    sa.Column('ai_extracted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meet_meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meet_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('host', 'moderator', 'member', 'guest', name='participantrole'), nullable=True),
    sa.Column('attendance_status', sa.Enum('invited', 'accepted', 'declined', 'attended', 'no_show', name='attendancestatus'), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meet_meeting.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meet_annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('target_artifact_id', sa.Integer(), nullable=True),
    sa.Column('annotation_type', sa.Enum('freehand', 'highlight', 'arrow', 'box', 'sticky_note', 'text_comment', 'pin', name='annotationtype'), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('source_timestamp', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meet_meeting.id'], ),
    sa.ForeignKeyConstraint(['target_artifact_id'], ['meet_artifact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_action'))
        batch_op.drop_index(batch_op.f('ix_activities_created_at'))
        batch_op.drop_index(batch_op.f('ix_activities_user_id'))

    op.drop_table('activities')
    op.drop_table('drive_files')
    with op.batch_alter_table('milestone_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestone_files_milestone_id'))

    op.drop_table('milestone_files')
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_column('activated_as_startup_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activated_as_startup_id', sa.INTEGER(), nullable=True))

    op.create_table('milestone_files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('milestone_id', sa.INTEGER(), nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), nullable=True),
    sa.Column('original_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('stored_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('file_category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_proof', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['goal_milestones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestone_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestone_files_milestone_id'), ['milestone_id'], unique=False)

    op.create_table('drive_files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('extension', sa.VARCHAR(length=20), nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('size_bytes', sa.INTEGER(), nullable=True),
    sa.Column('file_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('owner_user_id', sa.INTEGER(), nullable=True),
    sa.Column('startup_id', sa.INTEGER(), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('visibility_scope', sa.VARCHAR(length=50), nullable=True),
    sa.Column('knowledge_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('file_state', sa.VARCHAR(length=30), nullable=True),
    sa.Column('tags_json', sa.TEXT(), nullable=True),
    sa.Column('linked_milestone_id', sa.INTEGER(), nullable=True),
    sa.Column('linked_meeting_id', sa.INTEGER(), nullable=True),
    sa.Column('linked_task_id', sa.INTEGER(), nullable=True),
    sa.Column('summary_short', sa.TEXT(), nullable=True),
    sa.Column('summary_long', sa.TEXT(), nullable=True),
    sa.Column('extracted_text', sa.TEXT(), nullable=True),
    sa.Column('indexing_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('indexed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=255), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_action'), ['action'], unique=False)

    op.drop_table('meet_annotation')
    op.drop_table('meet_participant')
    op.drop_table('meet_decision')
    op.drop_table('meet_audit_log')
    op.drop_table('meet_artifact')
    op.drop_table('meet_action_item')
    op.drop_table('meet_meeting')
    # ### end Alembic commands ###
