"""add cancelled to join request status

Revision ID: 9198f8997faf
Revises: 387cd3adcce8
Create Date: 2026-03-02 23:33:50.730288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9198f8997faf'
down_revision = '387cd3adcce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'idea_collab_requests' in inspector.get_table_names():
        op.drop_table('idea_collab_requests')
    if 'join_requests' in inspector.get_table_names():
        with op.batch_alter_table('join_requests', schema=None) as batch_op:
            batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=8),
                   type_=sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='joinrequeststatus'),
                   existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='joinrequeststatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    op.create_table('idea_collab_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('idea_id', sa.INTEGER(), nullable=False),
    sa.Column('idea_title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
