"""add storage_used_mb to users

Revision ID: a07bba3604e0
Revises: dae228d06db0
Create Date: 2026-02-25 15:40:42.399903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07bba3604e0'
down_revision = 'dae228d06db0'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    def table_exists(table_name):
        return table_name in inspector.get_table_names()

    def column_exists(table_name, column_name):
        if not table_exists(table_name):
            return False
        return column_name in {column['name'] for column in inspector.get_columns(table_name)}

    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('pitch_decks'):
        op.create_table('pitch_decks',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('startup_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('template_type', sa.String(length=100), nullable=False),
        sa.Column('theme_type', sa.String(length=100), nullable=False),
        sa.Column('slides_json', sa.JSON(), nullable=False),
        sa.Column('credits_used', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if not table_exists('plan_versions'):
        op.create_table('plan_versions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plan_id', sa.Integer(), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('trigger_type', sa.String(length=50), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('health_score', sa.Integer(), nullable=True),
        sa.Column('health_status', sa.String(length=30), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['plan_id'], ['business_plans.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if not table_exists('startup_views'):
        op.create_table('startup_views',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('startup_id', sa.Integer(), nullable=False),
        sa.Column('viewed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if not table_exists('idea_comment_likes'):
        op.create_table('idea_comment_likes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('comment_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['comment_id'], ['idea_comments.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if table_exists('message_tasks'):
        op.drop_table('message_tasks')
    if table_exists('message_stars'):
        op.drop_table('message_stars')
    if table_exists('pinned_messages'):
        op.drop_table('pinned_messages')

    if table_exists('conversation_participants') and column_exists('conversation_participants', 'is_archived'):
        with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
            batch_op.alter_column('is_archived',
                   existing_type=sa.INTEGER(),
                   type_=sa.Boolean(),
                   existing_nullable=False,
                   existing_server_default=sa.text('0'))

    if table_exists('knowledge') and not column_exists('knowledge', 'file_size_mb'):
        with op.batch_alter_table('knowledge', schema=None) as batch_op:
            batch_op.add_column(sa.Column('file_size_mb', sa.Float(), nullable=True))

    if table_exists('plan_financials') and not column_exists('plan_financials', 'scenario'):
        with op.batch_alter_table('plan_financials', schema=None) as batch_op:
            batch_op.add_column(sa.Column('scenario', sa.String(length=20), nullable=True))

    if table_exists('users') and not column_exists('users', 'storage_used_mb'):
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('storage_used_mb', sa.Float(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('storage_used_mb')

    with op.batch_alter_table('plan_financials', schema=None) as batch_op:
        batch_op.drop_column('scenario')

    with op.batch_alter_table('knowledge', schema=None) as batch_op:
        batch_op.drop_column('file_size_mb')

    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.alter_column('is_archived',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    op.create_table('pinned_messages',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('conversation_id', sa.INTEGER(), nullable=False),
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.Column('pinned_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'message_id')
    )
    op.create_table('message_stars',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'message_id')
    )
    op.create_table('message_tasks',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), nullable=False),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('is_done', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'message_id')
    )
    op.drop_table('idea_comment_likes')
    op.drop_table('startup_views')
    op.drop_table('plan_versions')
    op.drop_table('pitch_decks')
    # ### end Alembic commands ###
