"""add drive_files table

Revision ID: c0c33aaa1426
Revises: cacdecb8e208
Create Date: 2026-04-25 15:11:58.496294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c33aaa1426'
down_revision = 'cacdecb8e208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('startup_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('visibility_scope', sa.String(length=50), nullable=True),
    sa.Column('knowledge_type', sa.String(length=50), nullable=True),
    sa.Column('file_state', sa.String(length=30), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('linked_milestone_id', sa.Integer(), nullable=True),
    sa.Column('linked_meeting_id', sa.Integer(), nullable=True),
    sa.Column('linked_task_id', sa.Integer(), nullable=True),
    sa.Column('summary_short', sa.Text(), nullable=True),
    sa.Column('summary_long', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('indexing_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drive_files')
    # ### end Alembic commands ###
