"""add crystals and visibility boosts

Revision ID: c18d8dd600f4
Revises: 9ba2df17d7b6
Create Date: 2026-03-12 22:53:09.196201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18d8dd600f4'
down_revision = '9ba2df17d7b6'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())

    def has_table(table_name):
        return table_name in tables

    def has_column(table_name, column_name):
        if not has_table(table_name):
            return False
        return any(col['name'] == column_name for col in inspector.get_columns(table_name))

    def has_index(table_name, index_name):
        if not has_table(table_name):
            return False
        return any(idx['name'] == index_name for idx in inspector.get_indexes(table_name))

    if has_table('users') and has_table('startups') and not has_table('startup_ratings'):
        op.create_table(
            'startup_ratings',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('startup_id', sa.Integer(), nullable=False),
            sa.Column('rating', sa.Float(), nullable=False),
            sa.Column('review_text', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['startup_id'], ['startups.id']),
            sa.ForeignKeyConstraint(['user_id'], ['users.id']),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('user_id', 'startup_id', name='unique_user_startup_rating')
        )

    # NOTE: Index drops from the autogenerated revision are intentionally skipped.
    # In MySQL these indexes may be required by existing foreign-key constraints,
    # and dropping them causes OperationalError 1553 on real environments.

    if has_table('event_token_balances'):
        with op.batch_alter_table('event_token_balances', schema=None) as batch_op:
            if not has_column('event_token_balances', 'event_name'):
                batch_op.add_column(sa.Column('event_name', sa.String(length=255), nullable=True))
            if not has_column('event_token_balances', 'earned_total'):
                batch_op.add_column(sa.Column('earned_total', sa.Integer(), nullable=True))
            if not has_column('event_token_balances', 'spent_total'):
                batch_op.add_column(sa.Column('spent_total', sa.Integer(), nullable=True))
            if not has_column('event_token_balances', 'expires_at'):
                batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    if has_table('idea_collab_requests') and has_column('idea_collab_requests', 'status'):
        with op.batch_alter_table('idea_collab_requests', schema=None) as batch_op:
            batch_op.alter_column(
                'status',
                existing_type=sa.VARCHAR(length=9),
                nullable=False
            )

    if has_table('startups'):
        with op.batch_alter_table('startups', schema=None) as batch_op:
            if has_column('startups', 'last_activity_at'):
                batch_op.alter_column(
                    'last_activity_at',
                    existing_type=sa.TIMESTAMP(),
                    type_=sa.DateTime(),
                    existing_nullable=True
                )
            if has_column('startups', 'crowdfunding_unlocked_at'):
                batch_op.alter_column(
                    'crowdfunding_unlocked_at',
                    existing_type=sa.TIMESTAMP(),
                    type_=sa.DateTime(),
                    existing_nullable=True
                )

    if has_table('suggestions') and has_column('suggestions', 'status'):
        with op.batch_alter_table('suggestions', schema=None) as batch_op:
            batch_op.alter_column(
                'status',
                existing_type=sa.VARCHAR(length=8),
                type_=sa.Enum('pending', 'accepted', 'rejected', 'cancelled', name='suggestionstatus'),
                existing_nullable=True
            )

    if has_table('transactions') and not has_column('transactions', 'stripe_payout_id'):
        with op.batch_alter_table('transactions', schema=None) as batch_op:
            batch_op.add_column(sa.Column('stripe_payout_id', sa.String(length=255), nullable=True))

    if has_table('users') and has_column('users', 'last_seen'):
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.drop_column('last_seen')

    # Visibility boost index drops are also skipped for the same compatibility reason.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visibility_boosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visibility_boosts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visibility_boosts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_visibility_boosts_expires_at'), ['expires_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('stripe_payout_id')

    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'accepted', 'rejected', 'cancelled', name='suggestionstatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.alter_column('crowdfunding_unlocked_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('last_activity_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('idea_collab_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)

    with op.batch_alter_table('event_token_balances', schema=None) as batch_op:
        batch_op.drop_column('expires_at')
        batch_op.drop_column('spent_total')
        batch_op.drop_column('earned_total')
        batch_op.drop_column('event_name')

    with op.batch_alter_table('escrow_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escrow_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_escrow_payer_id'), ['payer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_escrow_payee_id'), ['payee_id'], unique=False)

    with op.batch_alter_table('crystal_wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crystal_wallets_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('crystal_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crystal_transactions_wallet_id'), ['crystal_wallet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crystal_transactions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balances_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('balance_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_transactions_balance_id'), ['balance_id'], unique=False)

    op.drop_table('startup_ratings')
    # ### end Alembic commands ###
