"""add marketplace purchases

Revision ID: c6c067423ccb
Revises: 8792668c20b9
Create Date: 2026-03-17 18:10:45.660792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c067423ccb'
down_revision = '8792668c20b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('platform_fee_cents', sa.Integer(), nullable=False),
    sa.Column('seller_cut_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('buyer_tx_id', sa.Integer(), nullable=True),
    sa.Column('seller_tx_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('rated_at', sa.DateTime(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['marketplace_sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketplace_purchases')
    # ### end Alembic commands ###
