"""add milestone_files table

Revision ID: cacdecb8e208
Revises: fdde135e9006
Create Date: 2026-04-22 17:57:44.072789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cacdecb8e208'
down_revision = 'fdde135e9006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_category', sa.String(length=50), nullable=True),
    sa.Column('is_proof', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['goal_milestones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestone_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestone_files_milestone_id'), ['milestone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milestone_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestone_files_milestone_id'))

    op.drop_table('milestone_files')
    # ### end Alembic commands ###
