"""add startup ratings

Revision ID: ee78359866cc
Revises: 387cd3adcce8
Create Date: 2026-03-04 11:17:42.348188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee78359866cc'
down_revision = '387cd3adcce8'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    def table_exists(table_name):
        return table_name in inspector.get_table_names()

    def column_exists(table_name, column_name):
        if not table_exists(table_name):
            return False
        return column_name in {column['name'] for column in inspector.get_columns(table_name)}

    def index_exists(table_name, index_name):
        if not table_exists(table_name):
            return False
        return index_name in {index['name'] for index in inspector.get_indexes(table_name)}

    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('ai_news_articles'):
        op.create_table('ai_news_articles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('url', sa.String(length=750), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('author', sa.String(length=255), nullable=True),
        sa.Column('image_url', sa.String(length=750), nullable=True),
        sa.Column('source', sa.String(length=100), nullable=False),
        sa.Column('source_label', sa.String(length=100), nullable=True),
        sa.Column('category', sa.String(length=100), nullable=True),
        sa.Column('tags', sa.Text(), nullable=True),
        sa.Column('impact_score', sa.Integer(), nullable=True),
        sa.Column('published_at', sa.DateTime(), nullable=True),
        sa.Column('scraped_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url')
        )

    if not table_exists('pitch_decks'):
        op.create_table('pitch_decks',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('startup_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('template_type', sa.String(length=100), nullable=False),
        sa.Column('theme_type', sa.String(length=100), nullable=False),
        sa.Column('slides_json', sa.JSON(), nullable=False),
        sa.Column('credits_used', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not table_exists('plan_versions'):
        op.create_table('plan_versions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plan_id', sa.Integer(), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('trigger_type', sa.String(length=50), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('health_score', sa.Integer(), nullable=True),
        sa.Column('health_status', sa.String(length=30), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['plan_id'], ['business_plans.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not table_exists('startup_invitations'):
        op.create_table('startup_invitations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('startup_id', sa.Integer(), nullable=False),
        sa.Column('invited_user_id', sa.Integer(), nullable=False),
        sa.Column('invited_by_id', sa.Integer(), nullable=True),
        sa.Column('role', sa.String(length=100), nullable=False),
        sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'expired', name='invitationstatus'), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('responded_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('startup_id', 'invited_user_id', name='unique_startup_invitation')
        )
    if table_exists('activities'):
        with op.batch_alter_table('activities', schema=None) as batch_op:
            if not index_exists('activities', batch_op.f('ix_activities_action')):
                batch_op.create_index(batch_op.f('ix_activities_action'), ['action'], unique=False)
            if not index_exists('activities', batch_op.f('ix_activities_created_at')):
                batch_op.create_index(batch_op.f('ix_activities_created_at'), ['created_at'], unique=False)
            if not index_exists('activities', batch_op.f('ix_activities_user_id')):
                batch_op.create_index(batch_op.f('ix_activities_user_id'), ['user_id'], unique=False)

    if table_exists('conversation_participants'):
        with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
            if not column_exists('conversation_participants', 'is_archived'):
                batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False))
            if not column_exists('conversation_participants', 'archived_at'):
                batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
            if not column_exists('conversation_participants', 'is_pinned'):
                batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=False))
            if not column_exists('conversation_participants', 'pinned_at'):
                batch_op.add_column(sa.Column('pinned_at', sa.DateTime(), nullable=True))

    if table_exists('feedback'):
        with op.batch_alter_table('feedback', schema=None) as batch_op:
            if not index_exists('feedback', batch_op.f('ix_feedback_created_at')):
                batch_op.create_index(batch_op.f('ix_feedback_created_at'), ['created_at'], unique=False)

    if table_exists('plan_financials') and not column_exists('plan_financials', 'scenario'):
        with op.batch_alter_table('plan_financials', schema=None) as batch_op:
            batch_op.add_column(sa.Column('scenario', sa.String(length=20), nullable=True))

    if table_exists('startup_documents'):
        with op.batch_alter_table('startup_documents', schema=None) as batch_op:
            if not column_exists('startup_documents', 'file_size_mb'):
                batch_op.add_column(sa.Column('file_size_mb', sa.Float(), nullable=True))
            if column_exists('startup_documents', 'file_size'):
                batch_op.drop_column('file_size')

    if table_exists('users'):
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.alter_column('role',
                   existing_type=mysql.ENUM('founder', 'contributor', 'influencer', 'content_creator', 'community_manager', 'hr_specialist', 'investor', 'advisor', 'mentor', 'partner', 'admin', 'moderator', 'member', 'technical_lead', 'engineering_manager', 'backend_engineer', 'frontend_engineer', 'fullstack_engineer', 'mobile_engineer', 'software_architect', 'qa_engineer', 'test_automation_engineer', 'devops_engineer', 'cloud_engineer', 'sre', 'infrastructure_engineer', 'platform_engineer', 'cybersecurity_engineer', 'data_scientist', 'data_engineer', 'machine_learning_engineer', 'ai_engineer', 'mlops_engineer', 'data_analyst', 'ai_researcher', 'product_manager', 'product_owner', 'ux_designer', 'ui_designer', 'product_designer', 'ux_researcher', 'growth_engineer', 'growth_marketer', 'seo_specialist', 'content_strategist'),
                   type_=sa.Enum('founder', 'contributor', 'investor', 'advisor', 'mentor', 'partner', 'admin', 'moderator', 'member', 'technical_lead', 'engineering_manager', 'influencer', 'content_creator', 'community_manager', 'hr_specialist', 'backend_engineer', 'frontend_engineer', 'fullstack_engineer', 'mobile_engineer', 'software_architect', 'qa_engineer', 'test_automation_engineer', 'devops_engineer', 'cloud_engineer', 'sre', 'infrastructure_engineer', 'platform_engineer', 'cybersecurity_engineer', 'data_scientist', 'data_engineer', 'machine_learning_engineer', 'ai_engineer', 'mlops_engineer', 'data_analyst', 'ai_researcher', 'product_manager', 'product_owner', 'ux_designer', 'ui_designer', 'product_designer', 'ux_researcher', 'growth_engineer', 'growth_marketer', 'seo_specialist', 'content_strategist', name='userroles'),
                   existing_nullable=True)

    if table_exists('waitlist'):
        with op.batch_alter_table('waitlist', schema=None) as batch_op:
            batch_op.alter_column(
                'created_at',
                existing_type=mysql.DATETIME(),
                nullable=False,
                existing_server_default=sa.text('CURRENT_TIMESTAMP')
            )
            batch_op.alter_column(
                'referral_points',
                existing_type=mysql.INTEGER(),
                nullable=False,
                existing_server_default=sa.text("'0'")
            )
            batch_op.alter_column(
                'contribution_points',
                existing_type=mysql.INTEGER(),
                nullable=False,
                existing_server_default=sa.text("'0'")
            )
            batch_op.alter_column(
                'activity_points',
                existing_type=mysql.INTEGER(),
                nullable=False,
                existing_server_default=sa.text("'0'")
            )

            if index_exists('waitlist', batch_op.f('email')):
                batch_op.drop_index(batch_op.f('email'))
            if index_exists('waitlist', batch_op.f('ix_created_at')):
                batch_op.drop_index(batch_op.f('ix_created_at'))
            if index_exists('waitlist', batch_op.f('ix_email')):
                batch_op.drop_index(batch_op.f('ix_email'))
            if not index_exists('waitlist', batch_op.f('ix_waitlist_created_at')):
                batch_op.create_index(batch_op.f('ix_waitlist_created_at'), ['created_at'], unique=False)
            if not index_exists('waitlist', batch_op.f('ix_waitlist_email')):
                batch_op.create_index(batch_op.f('ix_waitlist_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waitlist_email'))
        batch_op.drop_index(batch_op.f('ix_waitlist_created_at'))
        batch_op.create_index(batch_op.f('ix_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('activity_points',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('contribution_points',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('referral_points',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('role',
               existing_type=sa.Enum('founder', 'contributor', 'investor', 'advisor', 'mentor', 'partner', 'admin', 'moderator', 'member', 'technical_lead', 'engineering_manager', 'influencer', 'content_creator', 'community_manager', 'hr_specialist', 'backend_engineer', 'frontend_engineer', 'fullstack_engineer', 'mobile_engineer', 'software_architect', 'qa_engineer', 'test_automation_engineer', 'devops_engineer', 'cloud_engineer', 'sre', 'infrastructure_engineer', 'platform_engineer', 'cybersecurity_engineer', 'data_scientist', 'data_engineer', 'machine_learning_engineer', 'ai_engineer', 'mlops_engineer', 'data_analyst', 'ai_researcher', 'product_manager', 'product_owner', 'ux_designer', 'ui_designer', 'product_designer', 'ux_researcher', 'growth_engineer', 'growth_marketer', 'seo_specialist', 'content_strategist', name='userroles'),
               type_=mysql.ENUM('founder', 'contributor', 'influencer', 'content_creator', 'community_manager', 'hr_specialist', 'investor', 'advisor', 'mentor', 'partner', 'admin', 'moderator', 'member', 'technical_lead', 'engineering_manager', 'backend_engineer', 'frontend_engineer', 'fullstack_engineer', 'mobile_engineer', 'software_architect', 'qa_engineer', 'test_automation_engineer', 'devops_engineer', 'cloud_engineer', 'sre', 'infrastructure_engineer', 'platform_engineer', 'cybersecurity_engineer', 'data_scientist', 'data_engineer', 'machine_learning_engineer', 'ai_engineer', 'mlops_engineer', 'data_analyst', 'ai_researcher', 'product_manager', 'product_owner', 'ux_designer', 'ui_designer', 'product_designer', 'ux_researcher', 'growth_engineer', 'growth_marketer', 'seo_specialist', 'content_strategist'),
               existing_nullable=True)

    with op.batch_alter_table('startup_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('file_size_mb')

    with op.batch_alter_table('plan_financials', schema=None) as batch_op:
        batch_op.drop_column('scenario')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_created_at'))

    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_column('pinned_at')
        batch_op.drop_column('is_pinned')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('is_archived')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('activities_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_activities_user_id'))
        batch_op.drop_index(batch_op.f('ix_activities_created_at'))
        batch_op.drop_index(batch_op.f('ix_activities_action'))

    op.drop_table('startup_invitations')
    op.drop_table('plan_versions')
    op.drop_table('pitch_decks')
    op.drop_table('ai_news_articles')
    # ### end Alembic commands ###
