"""add matchmaking fields to builder profiles

Revision ID: fa0f0cf73d71
Revises: a14c0aba6716
Create Date: 2026-03-28 00:36:26.679413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0f0cf73d71'
down_revision = 'a14c0aba6716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('roles_needed', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collaboration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vision_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('commitment', sa.String(length=100), nullable=True),
    sa.Column('equity', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vision_id'], ['visions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('sector_interests', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('execution_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('builder_profiles', schema=None) as batch_op:
        batch_op.drop_column('availability')
        batch_op.drop_column('execution_score')
        batch_op.drop_column('sector_interests')
        batch_op.drop_column('skill_tags')

    op.drop_table('collaboration_requests')
    op.drop_table('visions')
    # ### end Alembic commands ###
